<a href="https://colab.research.google.com/github/nitinlodhi019/Deep-Learning/blob/main/Backpropagation/Backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Backpropagation on regression problem
(linear funtion)

(MSE)

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.DataFrame({
    'cgpa': [8, 7, 6, 5],
    'resume score': [8, 9, 10, 12],
    'package' : [4, 5, 6, 7]
})

In [3]:
data

cgpa  resume score  package
0     8             8        4
1     7             9        5
2     6            10        6
3     5            12        7

##initialize the architecture of the neeural network

In [4]:
def initialize_parameter(layer_dims):
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1, L):
    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
  return parameters

In [5]:
initialize_parameter([2, 2, 1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [6]:
def linear_forward(A_prev, W, b):
  Z = np.dot(W.T, A_prev) + b

  return Z

In [7]:
#Forward Propagation
def L_layer_forward(X, parameters):
  A = X
  L = len(parameters) // 2

  for l in range(1, L+1):
    A_prev = A
    W1 = parameters['W' + str(l)]
    b1 = parameters['b' + str(l)]
    #print('A'+str(l-1)+': ', A_prev)
    #print('W'+str(l)+': ', W1)
    #print('b'+str(l)+': ', b1)
    #print('--'*20)

    A = linear_forward(A_prev, W1, b1)
    #print('A'+str(l)+': ', A)
    #print('**'*20)

  return A, A_prev

###For student 1

In [8]:
#For student 1
X = data[['cgpa', 'resume score']].values[0].reshape(2, 1)
y = data[['package']].values[0][0]

parameter = initialize_parameter([2, 2, 1])
y_hat, A1 = L_layer_forward(X, parameter)

In [9]:
y_hat = y_hat[0][0]

In [10]:
A1

array([[1.6],
       [1.6]])

In [11]:
def update_parameters(parameters, y, y_hat, A1, X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0] * X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0] * X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [12]:
update_parameters(parameter, y, y_hat, A1, X)

In [13]:
#Updated parameter
parameter

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

###For student 2


In [14]:
#For student 2
X = data[['cgpa', 'resume score']].values[1].reshape(2, 1)
y = data[['package']].values[1][0]

y_hat, A1 = L_layer_forward(X, parameter)

In [15]:
update_parameters(parameter, y, y_hat, A1, X)

<ipython-input-11-700fd26f9306>:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
<ipython-input-11-700fd26f9306>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
<ipython-input-11-700fd26f9306>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001

In [16]:
#Updated parameter
parameter

{'W1': array([[0.11458955, 0.1168776 ],
        [0.11458955, 0.1168776 ]]),
 'b1': array([[0.0019667],
        [0.0019667]]),
 'W2': array([[0.12712927],
        [0.12712927]]),
 'b2': array([[0.13612818]])}

###For student 3


In [17]:
#For student 3
X = data[['cgpa', 'resume score']].values[2].reshape(2, 1)
y = data[['package']].values[2][0]

y_hat, A1 = L_layer_forward(X, parameter)

In [18]:
update_parameters(parameter, y, y_hat, A1, X)

<ipython-input-11-700fd26f9306>:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
<ipython-input-11-700fd26f9306>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
<ipython-input-11-700fd26f9306>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001

In [19]:
parameter

{'W1': array([[0.12409711, 0.13272353],
        [0.12412266, 0.13276611]]),
 'b1': array([[0.00355129],
        [0.00355555]]),
 'W2': array([[0.14692424],
        [0.14731907]]),
 'b2': array([[0.15810417]])}

###For student 4


In [20]:
#For student 4
X = data[['cgpa', 'resume score']].values[3].reshape(2, 1)
y = data[['package']].values[3][0]

y_hat, A1 = L_layer_forward(X, parameter)

In [21]:
update_parameters(parameter, y, y_hat, A1, X)

<ipython-input-11-700fd26f9306>:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
<ipython-input-11-700fd26f9306>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
<ipython-input-11-700fd26f9306>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001

In [22]:
parameter

{'W1': array([[0.13482804, 0.15847776],
        [0.1349909 , 0.15884991]]),
 'b1': array([[0.00569748],
        [0.0057292 ]]),
 'W2': array([[0.17312488],
        [0.17534027]]),
 'b2': array([[0.18773702]])}

##Single code for implementation

In [23]:
parameters = initialize_parameter([2, 2, 1])
epochs = 5
for i in range(epochs):

  loss = []
  for j in range(data.shape[0]):
    X = data[['cgpa', 'resume score']].values[j].reshape(2, 1)
    y = data[['package']].values[j][0]

    y_hat, A1 = L_layer_forward(X, parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters, y, y_hat, A1, X)
    loss.append((y-y_hat)**2)

  print('epoch - ', i+1, 'loss - ', np.array(loss).mean())

parameters

epoch -  1 loss -  25.321744156025517
epoch -  2 loss -  18.320004165722047
epoch -  3 loss -  9.473661050729628
epoch -  4 loss -  3.2520938634031613
epoch -  5 loss -  1.3407132589299962


{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}

##Backpropagation using keras

In [24]:
import numpy as np
import pandas as pd
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [25]:
data = pd.DataFrame({
    'cgpa': [8, 7, 6, 5],
    'resume score': [8, 9, 10, 12],
    'package' : [4, 5, 6, 7]
})

In [26]:
data

cgpa  resume score  package
0     8             8        4
1     7             9        5
2     6            10        6
3     5            12        7

In [27]:
model = Sequential()

model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [28]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.get_weights()

[array([[-1.0491154 , -0.41159862],
        [-0.8839325 , -0.47329897]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.3942231],
        [ 0.3334136]], dtype=float32),
 array([0.], dtype=float32)]

In [30]:
new_weights = [np.array([[0.1, 0.1],
                         [0.1, 0.1]], dtype=np.float32),
               np.array([0., 0.], dtype=np.float32),
               np.array([[0.1],
                         [0.1]], dtype=np.float32),
               np.array([0.], dtype=np.float32)]

In [31]:
model.set_weights(new_weights)


In [32]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [33]:
Optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=Optimizer)

In [34]:
model.fit(data[['cgpa', 'resume score']].values, data['package'].values, epochs=75, verbose=1, batch_size=2)

Epoch 1/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 28.3005
Epoch 2/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 31.2531
Epoch 3/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 27.9750 
Epoch 4/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 29.1901
Epoch 5/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 27.0250  
Epoch 6/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25.4862 
Epoch 7/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 30.3588 
Epoch 8/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 25.1505 
Epoch 9/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.9416
Epoch 10/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 26.1523
Epoch 11/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 22.9538
Epoch 12/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 29.3917 
Epoch 13/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 24.2660
Epoch 14/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25.4043
Epoch 15/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 27.1239
Epoch 16/75
2/

In [35]:
model.get_weights()

[array([[0.26391247, 0.26391247],
        [0.26110405, 0.26110405]], dtype=float32),
 array([0.16305321, 0.16305321], dtype=float32),
 array([[0.26363882],
        [0.26363882]], dtype=float32),
 array([0.13577746], dtype=float32)]

#Backpropagation on Classification Problem
(Sigmoid Function)

(BinaryCrossEntropy)

In [36]:
import pandas as pd
import numpy as np


In [37]:
data = pd.DataFrame({
    'cgpa':[8, 7, 6, 5],
    'profile_score': [8, 9, 10, 5],
    'placed': [1, 1, 0, 0]
})

In [38]:
data

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [39]:
def initialize_parameter(layer_dims):
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1, L):
    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
  return parameters

In [40]:
#Utility Function
def sigmoid(Z):
  A = 1/(1 + np.exp(-Z))

  return A

In [42]:
def linear_forward(A_prev, W, b):

  Z = np.dot(W.T, A_prev) + b
  A = sigmoid(Z)

  return A

In [43]:
#Forward Propagation
def L_layer_forward(X, parameters):
  A = X
  L = len(parameters) // 2

  for l in range(1, L+1):
    A_prev = A
    W1 = parameters['W' + str(l)]
    b1 = parameters['b' + str(l)]
    #print('A'+str(l-1)+': ', A_prev)
    #print('W'+str(l)+': ', W1)
    #print('b'+str(l)+': ', b1)
    #print('--'*20)

    A = linear_forward(A_prev, W1, b1)
    #print('A'+str(l)+': ', A)
    #print('**'*20)

  return A, A_prev

In [44]:
def update_parameters(parameters, y, y_hat, A1, X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])* X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])* X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))

In [46]:
#For student 1
X = data[['cgpa', 'profile_score']].values[0].reshape(2, 1)
y = data[['placed']].values[0][0]

parameters = initialize_parameter([2, 2, 1])
y_hat, A1 = L_layer_forward(X, parameters)
y_hat = y_hat[0][0]

update_parameters(parameters, y, y_hat, A1, X)

print('Loss for this Student -- ', -y*np.log(y_hat) - (1-y)*np.log(1-y_hat))
parameters

Loss for this Student --  0.613402628898913


{'W1': array([[0.10005146, 0.10005146],
        [0.10005146, 0.10005146]]),
 'b1': array([[6.43254269e-06],
        [6.43254269e-06]]),
 'W2': array([[0.10038148],
        [0.10038148]]),
 'b2': array([[0.10083997]])}

In [48]:
#For student 2
X = data[['cgpa', 'profile_score']].values[1].reshape(2, 1)
y = data[['placed']].values[1][0]

y_hat, A1 = L_layer_forward(X, parameters)
y_hat = y_hat[0][0]

update_parameters(parameters, y, y_hat, A1, X)

print('Loss for this Student -- ', -y*np.log(y_hat) - (1-y)*np.log(1-y_hat))
parameters

Loss for this Student --  0.5681410379299662


{'W1': array([[0.10008773, 0.10011279],
        [0.10008772, 0.10011278]]),
 'b1': array([[1.25322278e-05],
        [1.25313946e-05]]),
 'W2': array([[0.10074214],
        [0.10074215]]),
 'b2': array([[0.10117557]])}

In [49]:
#For student 3
X = data[['cgpa', 'profile_score']].values[2].reshape(2, 1)
y = data[['placed']].values[2][0]

y_hat, A1 = L_layer_forward(X, parameters)
y_hat = y_hat[0][0]

update_parameters(parameters, y, y_hat, A1, X)

print('Loss for this Student -- ', -y*np.log(y_hat) - (1-y)*np.log(1-y_hat))
parameters

Loss for this Student --  0.8365856369934253


{'W1': array([[0.10004011, 0.10003343],
        [0.10004012, 0.10003344]]),
 'b1': array([[4.59628039e-06],
        [4.59756310e-06]]),
 'W2': array([[0.10027042],
        [0.10027041]]),
 'b2': array([[0.09970359]])}

In [50]:
#For student 4
X = data[['cgpa', 'profile_score']].values[3].reshape(2, 1)
y = data[['placed']].values[3][0]

y_hat, A1 = L_layer_forward(X, parameters)
y_hat = y_hat[0][0]

update_parameters(parameters, y, y_hat, A1, X)

print('Loss for this Student -- ', -y*np.log(y_hat) - (1-y)*np.log(1-y_hat))
parameters

Loss for this Student --  0.8238752892053788


{'W1': array([[0.09998502, 0.09997834],
        [0.09998503, 0.09997835]]),
 'b1': array([[-6.42148441e-06],
        [-6.42054041e-06]]),
 'W2': array([[0.09986006],
        [0.09986005]]),
 'b2': array([[0.09929877]])}

##Single Code

In [52]:
parameters = initialize_parameter([2, 2, 1])
epochs = 50
for i in range(epochs):

  loss = []
  for j in range(data.shape[0]):
    X = data[['cgpa', 'profile_score']].values[j].reshape(2, 1)
    y = data[['placed']].values[j][0]

    y_hat, A1 = L_layer_forward(X, parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters, y, y_hat, A1, X)
    loss.append(-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

  print('epoch - ', i+1, 'loss - ', np.array(loss).mean())

parameters

epoch -  1 loss -  0.71050114771481
epoch -  2 loss -  0.6993819908638181
epoch -  3 loss -  0.6993584295593506
epoch -  4 loss -  0.6993349670157292
epoch -  5 loss -  0.6993116027845855
epoch -  6 loss -  0.6992883364197799
epoch -  7 loss -  0.6992651674773883
epoch -  8 loss -  0.6992420955156897
epoch -  9 loss -  0.6992191200951554
epoch -  10 loss -  0.6991962407784353
epoch -  11 loss -  0.699173457130348
epoch -  12 loss -  0.6991507687178667
epoch -  13 loss -  0.6991281751101095
epoch -  14 loss -  0.6991056758783265
epoch -  15 loss -  0.6990832705958882
epoch -  16 loss -  0.699060958838274
epoch -  17 loss -  0.6990387401830616
epoch -  18 loss -  0.699016614209914
epoch -  19 loss -  0.6989945805005696
epoch -  20 loss -  0.6989726386388295
epoch -  21 loss -  0.698950788210548
epoch -  22 loss -  0.6989290288036194
epoch -  23 loss -  0.6989073600079687
epoch -  24 loss -  0.6988857814155395
epoch -  25 loss -  0.6988642926202835
epoch -  26 loss -  0.6988428932181494
e

{'W1': array([[0.09950872, 0.09857616],
        [0.09951369, 0.09857676]]),
 'b1': array([[-0.00031786],
        [-0.00031795]]),
 'W2': array([[0.09240871],
        [0.0924183 ]]),
 'b2': array([[0.09186164]])}

##Use Keras

In [54]:
import numpy as np
import pandas as pd

In [55]:
data = pd.DataFrame({
    'cgpa':[8, 7, 6, 5],
    'profile_score': [8, 9, 10, 5],
    'placed': [1, 1, 0, 0]
})

In [56]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [58]:
model = Sequential()

model.add(Dense(2, activation='sigmoid', input_dim=2))
model.add(Dense(1, activation='sigmoid'))

In [59]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                      │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [60]:
model.get_weights()

[array([[0.33583844, 0.55260694],
        [0.2745279 , 0.35317516]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.5917542],
        [ 1.0045019]], dtype=float32),
 array([0.], dtype=float32)]

In [61]:
new_weights = [np.array([[0.1, 0.1],
                         [0.1, 0.1]], dtype=np.float32),
               np.array([0., 0.], dtype=np.float32),
               np.array([[0.1],
                         [0.1]], dtype=np.float32),
               np.array([0.], dtype=np.float32)]

In [63]:
model.set_weights(new_weights)

In [64]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy', optimizer=optimizer)

In [65]:
model.fit(data[['cgpa', 'profile_score']].values, data['placed'].values, epochs=50, verbose=1, batch_size=1)

Epoch 1/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.6565
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.7148 
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.7144 
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6713 
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6713 
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6713 
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6732  
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6565 
Epoch 9/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7328 
Epoch 10/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6717 
Epoch 11/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6827 
Epoch 12/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.7064 
Epoch 13/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6737 
Epoch 14/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6827 
Epoch 15/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6570 
Epoch 16/50
4/4 ━━━━━━━━━━━━━━━━━━