<a href="https://colab.research.google.com/github/nitinlodhi019/Deep-Learning/blob/main/Backpropagation/Backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Backpropagation on regression problem

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.DataFrame({
    'cgpa': [8, 7, 6, 5],
    'resume score': [8, 9, 10, 12],
    'package' : [4, 5, 6, 7]
})

In [3]:
data

cgpa  resume score  package
0     8             8        4
1     7             9        5
2     6            10        6
3     5            12        7

##initialize the architecture of the neeural network

In [4]:
def initialize_parameter(layer_dims):
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1, L):
    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
  return parameters

In [5]:
initialize_parameter([2, 2, 1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [6]:
def linear_forward(A_prev, W, b):
  Z = np.dot(W.T, A_prev) + b

  return Z

In [33]:
#Forward Propagation
def L_layer_forward(X, parameters):
  A = X
  L = len(parameters) // 2

  for l in range(1, L+1):
    A_prev = A
    W1 = parameters['W' + str(l)]
    b1 = parameters['b' + str(l)]
    #print('A'+str(l-1)+': ', A_prev)
    #print('W'+str(l)+': ', W1)
    #print('b'+str(l)+': ', b1)
    #print('--'*20)

    A = linear_forward(A_prev, W1, b1)
    #print('A'+str(l)+': ', A)
    #print('**'*20)

  return A, A_prev

###For student 1

In [15]:
#For student 1
X = data[['cgpa', 'resume score']].values[0].reshape(2, 1)
y = data[['package']].values[0][0]

parameter = initialize_parameter([2, 2, 1])
y_hat, A1 = L_layer_forward(X, parameter)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


In [16]:
y_hat = y_hat[0][0]

In [17]:
A1

array([[1.6],
       [1.6]])

In [14]:
def update_parameters(parameters, y, y_hat, A1, X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0] * X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0] * X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [18]:
update_parameters(parameter, y, y_hat, A1, X)

In [19]:
#Updated parameter
parameter

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

###For student 2


In [22]:
#For student 2
X = data[['cgpa', 'resume score']].values[1].reshape(2, 1)
y = data[['package']].values[1][0]

y_hat, A1 = L_layer_forward(X, parameter)

A0:  [[7]
 [9]]
W1:  [[0.10753323 0.10968558]
 [0.10753323 0.10968558]]
b1:  [[0.00107618]
 [0.00107618]]
----------------------------------------
A1:  [[1.72160782]
 [1.75604543]]
****************************************
A1:  [[1.72160782]
 [1.75604543]]
W2:  [[0.114976]
 [0.114976]]
b2:  [[0.124336]]
----------------------------------------
A2:  [[0.52418266]]
****************************************


In [23]:
update_parameters(parameter, y, y_hat, A1, X)

<ipython-input-14-700fd26f9306>:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
<ipython-input-14-700fd26f9306>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
<ipython-input-14-700fd26f9306>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001

In [24]:
#Updated parameter
parameter

{'W1': array([[0.11570348, 0.12019019],
        [0.11572279, 0.12021502]]),
 'b1': array([[0.00224335],
        [0.00224611]]),
 'W2': array([[0.1303872 ],
        [0.13069548]]),
 'b2': array([[0.13964711]])}

###For student 3


In [25]:
#For student 3
X = data[['cgpa', 'resume score']].values[2].reshape(2, 1)
y = data[['package']].values[2][0]

y_hat, A1 = L_layer_forward(X, parameter)

A0:  [[ 6]
 [10]]
W1:  [[0.11570348 0.12019019]
 [0.11572279 0.12021502]]
b1:  [[0.00224335]
 [0.00224611]]
----------------------------------------
A1:  [[1.85369217]
 [1.92553745]]
****************************************
A1:  [[1.85369217]
 [1.92553745]]
W2:  [[0.1303872 ]
 [0.13069548]]
b2:  [[0.13964711]]
----------------------------------------
A2:  [[0.63300389]]
****************************************


In [26]:
update_parameters(parameter, y, y_hat, A1, X)

<ipython-input-14-700fd26f9306>:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
<ipython-input-14-700fd26f9306>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
<ipython-input-14-700fd26f9306>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001

In [27]:
parameter

{'W1': array([[0.12538241, 0.13632174],
        [0.12547125, 0.13646244]]),
 'b1': array([[0.00385651],
        [0.00387086]]),
 'W2': array([[0.15028472],
        [0.15136418]]),
 'b2': array([[0.16209817]])}

###For student 4


In [28]:
#For student 4
X = data[['cgpa', 'resume score']].values[3].reshape(2, 1)
y = data[['package']].values[3][0]

y_hat, A1 = L_layer_forward(X, parameter)

A0:  [[ 5]
 [12]]
W1:  [[0.12538241 0.13632174]
 [0.12547125 0.13646244]]
b1:  [[0.00385651]
 [0.00387086]]
----------------------------------------
A1:  [[2.13642351]
 [2.32302883]]
****************************************
A1:  [[2.13642351]
 [2.32302883]]
W2:  [[0.15028472]
 [0.15136418]]
b2:  [[0.16209817]]
----------------------------------------
A2:  [[0.83479334]]
****************************************


In [29]:
update_parameters(parameter, y, y_hat, A1, X)

<ipython-input-14-700fd26f9306>:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
<ipython-input-14-700fd26f9306>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
<ipython-input-14-700fd26f9306>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001

In [30]:
parameter

{'W1': array([[0.13627187, 0.16245645],
        [0.13656912, 0.16309733]]),
 'b1': array([[0.0060344 ],
        [0.00609043]]),
 'W2': array([[0.17662771],
        [0.18000809]]),
 'b2': array([[0.1923385]])}

##Single code for implementation

In [35]:
parameters = initialize_parameter([2, 2, 1])
epochs = 5
for i in range(epochs):

  loss = []
  for j in range(data.shape[0]):
    X = data[['cgpa', 'resume score']].values[j].reshape(2, 1)
    y = data[['package']].values[j][0]

    y_hat, A1 = L_layer_forward(X, parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters, y, y_hat, A1, X)
    loss.append((y-y_hat)**2)

  print('epoch - ', i+1, 'loss - ', np.array(loss).mean())

parameters

epoch -  1 loss -  25.321744156025517
epoch -  2 loss -  18.320004165722047
epoch -  3 loss -  9.473661050729628
epoch -  4 loss -  3.2520938634031613
epoch -  5 loss -  1.3407132589299962


{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}

#Backpropagation using keras

In [36]:
import numpy as np
import pandas as pd
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [37]:
data = pd.DataFrame({
    'cgpa': [8, 7, 6, 5],
    'resume score': [8, 9, 10, 12],
    'package' : [4, 5, 6, 7]
})

In [38]:
data

cgpa  resume score  package
0     8             8        4
1     7             9        5
2     6            10        6
3     5            12        7

In [39]:
model = Sequential()

model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [40]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [41]:
model.get_weights()

[array([[0.84811175, 0.5264591 ],
        [0.62659466, 1.0118784 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.05603647],
        [0.5879139 ]], dtype=float32),
 array([0.], dtype=float32)]

In [42]:
new_weights = [np.array([[0.1, 0.1],
                         [0.1, 0.1]], dtype=np.float32),
               np.array([0., 0.], dtype=np.float32),
               np.array([[0.1],
                         [0.1]], dtype=np.float32),
               np.array([0.], dtype=np.float32)]

In [43]:
model.set_weights(new_weights)


In [44]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [45]:
Optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=Optimizer)

In [46]:
model.fit(data[['cgpa', 'resume score']].values, data['package'].values, epochs=75, verbose=1, batch_size=2)

Epoch 1/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 24.5523
Epoch 2/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 27.5181 
Epoch 3/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 27.3563
Epoch 4/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 29.1899
Epoch 5/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 29.0153 
Epoch 6/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26.8542 
Epoch 7/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 28.6589
Epoch 8/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 25.1483 
Epoch 9/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 23.2909 
Epoch 10/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.1231 
Epoch 11/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 27.9147
Epoch 12/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 26.3850 
Epoch 13/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 24.2639 
Epoch 14/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 26.0011 
Epoch 15/75
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 23.8906
Epoch 16/75
2/2 ━━━

In [48]:
model.get_weights()

[array([[0.26393276, 0.26393276],
        [0.26188782, 0.26188782]], dtype=float32),
 array([0.1634251, 0.1634251], dtype=float32),
 array([[0.26406097],
        [0.26406097]], dtype=float32),
 array([0.13601834], dtype=float32)]